### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by aarnif** [Eldemarkki/keskustelusovellus#1]
### Tietokannan rakenne:

Tietokantataulukot mielestäni hyvin tehdyt.

### Koodi:

App.py-tiedostossa olevan koodin voisi jakaa useampaan tiedostoon (esim routeille ja tietokantakyselyille omat tiedostot).

Muita html-tiedostoja voi extendaa esim. layout.html-tiedostolla,
mihin laitat esim. html-sivujen title- ja meta-tiedot (pääsee eroon toisteisesta koodista). Ohjeet tähän:
https://hy-tsoha.github.io/materiaali/osa-4/#ulkoasun-toteutus.

### Sovelluksen käyttö:

Käyttäjän rekisteröinti ja kirjautuminen toimii hyvin.

Jos käyttäjä luo alueen ilman ketjuja, niin aluetta ei näy etusivulla (ilmestyy kuitenkin tietokantaan).

Käyttäjä voi luoda ketjun alueeseen ilman otsikkoa ja/tai aloitusviestiä (onko tarkoituksellista?).

### Yhteenveto:

Hyvällä mallilla oleva sovellus kokonaisuudessa.

**Comment by Eldemarkki** [comment]
Kiitos palautteesta, nämä pitäisi nyt olla korjattu!
