### ISSUE TITLE
Vertaisarviointi (välipalautus #3)

### ISSUE THREAD

**Issue by akselipu** [Eldemarkki/keskustelusovellus#2]
- Sovelluksen osat toimivat hienosti ja niin kuin pitääkin
- Koodi on hyvin jäsenneltyä ja ymmärrettävää
- Ympäristömuuttujia käytetty oikein
- Commitit hyviä

- Käynnistysohjeet hieman vajavaiset, joten sovelluksen käynnistämisessä meni hetki.
    - Voisi olla ohje miten Docker käynnistetään, jonka jälkeen tietokantojen käynnistys onnistuu
    - Docker ei ole minulle hirveän tuttu mutta pitäisiköhän READMEssä olevan koodin "-f docker-compose.dev.yml up" 
       lopussa olla vielä -d, jotta container käynnistyisi taustalla?
- Kun rekisteröin käyttäjän sovellus ilmoittaa "tervetuloa takaisin, 'nimi' "
- Lisäksi käyttäjää rekisteröidessä olisi hyvä pyytää salasana kahteen kertaan

Kaiken kaikkiaan sovellus on todella hyvällä mallilla ja mukava käyttää. Pieniä viilauksia vaille valmis.

**Comment by Eldemarkki** [comment]
Kiitos palautteesta!
